### ISSUE TITLE
[Anilist] Anime Info no result on some anime IDs

### ISSUE THREAD

**Issue by Ozakinn** [consumet/api.consumet.org#156]
### Describe the bug

Returns nothings but anilist has info about it.

### Steps to reproduce

1. I found this anime 
`https://api.consumet.org/meta/anilist/advanced-search?perPage=50&query=yahari%20ore%20no%20seishun`
2. Use Anime Info id=14813
`https://api.consumet.org/meta/anilist/info/14813`
3. It returns
`{"message":{}}`

### Expected behavior

I expect it to return json string along with anime title, image, cover, release date, episodes, characters, and a lot more info.
The API seems doesnt have info about it but anilist has it.
https://anilist.co/anime/14813/Yahari-Ore-no-Seishun-Love-Come-wa-Machigatteiru/

### Actual behavior

Returns
`{"message":{}}`
Instead of something like this
`{"id":"20","title":{"romaji":"NARUTO","english":"Naruto","native":"NARUTO -ナルト-"},"malId":20,"synonyms":["נארוטו","ناروتو","火影忍者","นารูโตะ นินจาจอมคาถา"],"isLicensed":true,"isAdult":false,"countryOfOrigin":"JP","image":"https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx20-YJvLbgJQPCoI.jpg","popularity":429649,"color":"#e47850","cover":"https://s4.anilist.co/file/anilistcdn/media/anime/banner/20-HHxhPj5JD13a.jpg","description":"Naruto Uzumaki, a hyperactive and knuckle-headed ninja, lives in Konohagakure, the Hidden Leaf village. Moments prior to his birth, a huge demon known as the Kyuubi, the Nine-tailed Fox, attacked Konohagakure and wreaked havoc. In order to put an end to the Kyuubi's rampage, the leader of the village, the 4th Hokage, sacrificed his life and sealed the monstrous beast inside the newborn Naruto. <br><br>\nShunned because of the presence of the Kyuubi inside him, Naruto struggles to find his place in the village. He strives to become the Hokage of Konohagakure, and he meets many friends and foes along the way. <br><br>\n(Source: MAL Rewrite)","status":"Completed","releaseDate":2002,"startDate":{"year":2002,"month":10,"day":3},................................ more info"`

**Comment by riimuru** [comment]
fixed 👍
