### ISSUE TITLE
Anilist Api Not Working

### ISSUE THREAD

**Issue by TechShreyash** [consumet/api.consumet.org#180]
### Describe the bug

Api Error

### Steps to reproduce

If i try to get this https://api.consumet.org/meta/anilist/popular

Error comes... The same with search and anime info

### Expected behavior

List of trending animes and their data

### Actual behavior

{"statusCode":500,"error":"Internal Server Error","message":"Request failed with status code 429"}

**Comment by riimuru** [comment]
@TechShreyash Anilist is currently performing maintenance. It should be functional again soon.

**Comment by riimuru** [comment]
@TechShreyash Everything is back up  👍. Thanks for reporting.

**Comment by TechShreyash** [comment]
> @TechShreyash Anilist is currently performing maintenance. It should be functional again soon.

Oh ic

> @TechShreyash Everything is back up 👍. Thanks for reporting.

Okk thanku
