### ISSUE TITLE
Anilist info metadata sometimes returns error

### ISSUE THREAD

**Issue by ICEPrey** [consumet/api.consumet.org#187]
### Describe the bug

https://api.consumet.org/meta/anilist/info/5114

### Steps to reproduce

Go to the link above
refresh maybe a couple times?

### Expected behavior

To return data 

### Actual behavior

Returns error saying "Cannot read properties of undefined (reading 'mal')"
![image](https://user-images.githubusercontent.com/40725969/201535561-a76bb557-4b1d-456e-94a7-e478a789171b.png)
![image](https://user-images.githubusercontent.com/40725969/201535572-d8d1b639-0197-4fa6-997e-509e5fe544a4.png)

**Comment by illusionTBA** [comment]
Works for me. It may be bcs anilist servers are on and off rn

**Comment by ICEPrey** [comment]
Anilist issue
