### ISSUE TITLE
RIP Animixplay

### ISSUE THREAD

**Issue by pitsi** [consumet/api.consumet.org#234]
### Describe the bug

As seen in the screenshot below, animixplay shut down yesterday.

### Steps to reproduce

Use the api to search for something, e.g.
```
$ curl -s https://api.consumet.org/anime/animixplay/dragonball | jq .
{
  "results": [
    {
      "id": "/v1/dragon-ball",
      "title": "Dragon Ball",
      "url": "https://animixplay.to/v1/dragon-ball"
    },
    {
      "id": "/v1/dragon-ball-dub",
      "title": "Dragon Ball (Dub)",
      "url": "https://animixplay.to/v1/dragon-ball-dub"
    },
    {
      "id": "/v1/dragon-ball-gt",
      "title": "Dragon Ball GT",
      "url": "https://animixplay.to/v1/dragon-ball-gt"
    },
    {
      "id": "/v1/dragon-ball-gt-dub",
      "title": "Dragon Ball GT (Dub)",
      "url": "https://animixplay.to/v1/dragon-ball-gt-dub"
    },
    {
      "id": "/v1/dragon-ball-kai",
      "title": "Dragon Ball Kai",
      "url": "https://animixplay.to/v1/dragon-ball-kai"
    },
    {
      "id": "/v1/dragon-ball-kai-2014",
      "title": "Dragon Ball Kai (2014)",
      "url": "https://animixplay.to/v1/dragon-ball-kai-2014"
    }
  ]
}
```

### Expected behavior

Any of the above entries that are under the url keys should point to a valid page...

### Actual behavior

However, every url under the forementioned domain redirects to the main page where the user sees the following announcemet.

![2022-12-24-121048_1280x1024_scrot](https://user-images.githubusercontent.com/5880037/209431773-6a58cf43-c57a-44bd-8189-1d959a19b579.png)

### Additional context

This is as far as I could go with the api's functions. All I found from the source code is that it has 3 functions (search, info and watch), but I could not make any of the other 2 work.
Sadly, the api's part for animixplay is not documented under docs.consumet.org (and for other supported sites too) and my knowledge is too limited to understand the rest :(

**Comment by wearrrrr** [comment]
There is already a PR open in consumet.ts to deprecate animixplay
