### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by SlideMovies** [consumet/api.consumet.org#249]
### Describe the bug

api.consumet.org shows 503, or keeps loading.

### Steps to reproduce

Just load the URL.

### Expected behavior

It gives a response

### Actual behavior

It keeps on loading, or shows a 503 error

**Comment by illusionTBA** [comment]
This is because api.consumet.org received over 2 million requests yesterday so rem is trying to find a good auto scale config. Should be back up in a bit or you could just host your own

**Comment by riimuru** [comment]
fixed
