### ISSUE TITLE
Animepahe api end point is throwing an internal server error

### ISSUE THREAD

**Issue by sunder-kirei** [consumet/api.consumet.org#285]
### Describe the bug

Error code 500

### Steps to reproduce

Try querying a search on /animepahe/{query}

### Expected behavior

JSON Response is expected 

### Actual behavior

Error thrown

**Comment by TDanks2000** [comment]
> ### Describe the bug
> Error code 500
> 
> ### Steps to reproduce
> Try querying a search on /animepahe/{query}
> 
> ### Expected behavior
> JSON Response is expected
> 
> ### Actual behavior
> Error thrown
> 
> ### Additional context
> _No response_

it's because we have changed around the cors proxy url

**Comment by riimuru** [comment]
@sunder-kirei fixed 👍

**Comment by sunder-kirei** [comment]
Well, now the /watch api is broken😅
