### ISSUE TITLE
Flixhq Api down

### ISSUE THREAD

**Issue by HasanAbbadi** [consumet/api.consumet.org#310]
### Describe the bug

the flixHQ movies api stopped working

### Steps to reproduce

1. enter https://docs.consumet.org/rest-api/Movies/flixhq/search
2. Access denied, Error: 1020

### Expected behavior

should work fine and return results

### Actual behavior

api down with error 1020

**Comment by TDanks2000** [comment]
flixHQ has been disabled for the time being sorry for the inconvenience

**Comment by TDanks2000** [comment]
you can also join the discord for announcements [discord](https://discord.gg/qTPfvMxzNH)

**Comment by HasanAbbadi** [comment]
is it temporary?

**Comment by TDanks2000** [comment]
> is it temporary?

yes indeed, please bear with us

**Comment by riimuru** [comment]
@HasanAbbadi yes, but I fixed the link you sent if you want to check the docs: https://docs.consumet.org/rest-api/Movies/flixhq/search

**Comment by pitsi** [comment]
Flixhq is still down for me. After the 1020 error during the weekend, it was redirecting to a failed anime search yesterday (= Monday 13th) and today (Tuesday 14th) it redirects to sumi.im!

**Comment by illusionTBA** [comment]
Flixhq will stay down for the time being.

**Comment by pitsi** [comment]
Thank you for the clarificarion. Can you please open this issue until it is restored?
I was about to open an issue for it yesterday and I found no relevant open issues. Although I check for closed issues very rarely, this time I did and found this one, so I did not open a new one and subscribed here so as to be informed on when it will be resolved.

**Comment by illusionTBA** [comment]
btw you can still use the flixhq route by hosting your own instance or using someone elses. here's mine: https://c.delusionz.xyz/

**Comment by pitsi** [comment]
Will you mind if I use your instance once or twice a day to watch something?
I do not use docker or npm to set one instance for me :(

**Comment by gabinfinity** [comment]
> btw you can still use the flixhq route by hosting your own instance or using someone elses. here's mine: https://c.delusionz.xyz/

where can i find it to self hosted

**Comment by TDanks2000** [comment]
> > btw you can still use the flixhq route by hosting your own instance or using someone elses. here's mine: https://c.delusionz.xyz/
> 
> where can i find it to self hosted

on this repo

**Comment by gabinfinity** [comment]
thank you

**Comment by illusionTBA** [comment]
> Will you mind if I use your instance once or twice a day to watch something? I do not use docker or npm to set one instance for me :(

use it as much as you like

**Comment by pitsi** [comment]
After yesterday's commit, flixhq is working again (at least on my end), so this can be closed now.
Thank you very much!
