### ISSUE TITLE
rabbitstream key not working

### ISSUE THREAD

**Issue by XanXus96** [consumet/api.consumet.org#318]
### Describe the bug

the key in rapidclown rabbitstream branch isn't working and the action of the update isn't lanching at all

### Steps to reproduce

test the rabbitstream key

### Expected behavior

key working

### Actual behavior

key not working

**Comment by riimuru** [comment]
That repo was not made for public use to be maintained, you should try using this repo instead https://github.com/enimax-anime/key it should be consistent for the time being.

**Comment by XanXus96** [comment]
> That repo was not made for public use to be maintained, you should try using this repo instead https://github.com/enimax-anime/key it should be consistent for the time being.

it's not working for rabbitstream, btw in rapidclown the main branch key works sometimes for rabbitstream and sometimes not it's as if the current key works then the next one don't and it goes like that
