### ISSUE TITLE
flixhq routes redirecting to 9anime

### ISSUE THREAD

**Issue by JamesHawkinss** [consumet/api.consumet.org#326]
### Describe the bug

flixhq provider is not working

### Steps to reproduce

1. Navigate to https://api.consumet.org/movies/flixhq/info?id=tv/watch-vincenzo-67955

### Expected behavior

Returns JSON response

### Actual behavior

Redirects to 9anime

**Comment by wearrrrr** [comment]
flixHQ providers are currently non operational on the main deployment, please host your own instance or use a deployment such as https://api.haikei.xyz!

**Comment by HasanAbbadi** [comment]
> flixHQ providers are currently non operational on the main deployment, please host your own instance or use a deployment such as https://api.haikei.xyz!

No instances are working right now, not the main deployment not the one you've given, not even my self-hosted instance.
It either responds with 502 or media not found.
Please fix this soon, Thanks.

**Comment by riimuru** [comment]
fixed
