### ISSUE TITLE
Streaming Link Not currently working

### ISSUE THREAD

**Issue by Joelketema** [consumet/api.consumet.org#375]
### Describe the bug

500 Internal Server Error when requesting streaming link of a movie

### Steps to reproduce

Try to access the streaming link endpoint of movies

### Expected behavior

The response should be a streaming link with different qualities

### Actual behavior

It returns server error code 500, with the message Something went wrong. Please try again later.

**Comment by Estifanos12** [comment]
Same here - 500 server error response

**Comment by Compound-Z** [comment]
I have the same problem

**Comment by Compound-Z** [comment]
I tested with flixHQ route.
I tested the api source code, the problem is something with Json format. I think it was because the FlixHQ from Consumet extension. Is it posible that the flixHQ original website changed their response format?

**Comment by pitsi** [comment]
Just a head's up. The api's flixhq route is working on my end since a few days ago.
Not on the default instance though, because that one still leads to 9anime, but on a different one.

**Comment by Compound-Z** [comment]
Lol. It dies again :)))

**Comment by snoofox** [comment]
flixHQ is dead for me too

**Comment by riimuru** [comment]
@snoofox flixhq is working, you just need to self-host the api for it to work.

**Comment by snoofox** [comment]
@riimuru Thanks for the reply :3, I am already using self hosted API and everything was running smoothly till yesterday, but the `fetchEpisodeSources` and `fetchEpisodeServers` methods aren't working, it'll be big help if you look into it :)

**Comment by riimuru** [comment]
@snoofox Slr, I just tested it, and it's been working fine. try to delete the .lock files, and reinstall packages.
