### ISSUE TITLE
Zoro "/watch" endpoint broken.

### ISSUE THREAD

**Issue by gaminglnk** [consumet/api.consumet.org#386]
### Describe the bug

Zoro isn't providing video data, while fetching from the link given in docs, "https://api.consumet.org/anime/zoro/watch?episodeId=spy-x-family-17977$episode$89506$dub"

### Steps to reproduce

Just, try accessing any episode from "/watch" endpoint.
E.g.
[**Classroom of the Elite**](https://api.consumet.org/anime/zoro/watch?episodeId=spy-x-family-17977$episode$89506$both)

### Expected behavior

This should provide the :
- Episode HLS manifest.
- Subtitles.
- Preview Thumbnails.

### Actual behavior

The response given is, `{"message":{}}` with status code **404**.

### Additional context

I just made a direct anime player for Iframe embeds based on the API and in just an hour this problem occured.

The player works with using episode Id : [https://speedynet.eu.org/apps/anime/zoro?id={episodeId}](https://speedynet.eu.org/apps/anime/zoro?id=spy-x-family-17977$episode$89506$dub)

**Comment by riimuru** [comment]
@gaminglnk the zoro links should be working fine now. but you need to use a cors proxy to bypass the cors errors you're having on your player. check [cors anywhere](https://github.com/Rob--W/cors-anywhere) for more information.
