### ISSUE TITLE
Some anime data exactly array of episode return empty array example ['black clover', 'Koe no Katachi']

### ISSUE THREAD

**Issue by animotime-v3** [consumet/api.consumet.org#387]
### Describe the bug

the return empty array of episode in some anime and movies when navigating to anilist/meta/info /:id

### Steps to reproduce

1 : we navigate to https://api.consumet.org/meta/anilist/info/21519 [anime movie is kimi-no-na-wa]
2: we get the data object down we can see the episode array empty []
3: we navigate to hhttps://api.consumet.org/anime/gogoanime/watch/kimi-no-na-wa-episode-1
4: we got the streamming links
so the question is why we got some episodes links but others not ? 

### Expected behavior

to get : the episode array full of episode id and the other field

### Actual behavior

we got empty array

**Comment by fedryane** [comment]
also i got same result on BORUTO NEXT GEN (https://api.consumet.org/meta/anilist/info/97938)

**Comment by riimuru** [comment]
fixed
