### ISSUE TITLE
Crunchyroll search not working

### ISSUE THREAD

**Issue by JannisDev** [consumet/api.consumet.org#403]
### Describe the bug

Crunchyroll search is not working

### Steps to reproduce

Get 'https://api.consumet.org/anime/crunchyroll/attack'

### Expected behavior

Returning something like this:

{
            "id": "attack-on-tomorrow.kvm4",
            "title": "Attack on Tomorrow",
            "url": "https://9anime.pl/watch/attack-on-tomorrow.kvm4",
            "image": "https://static.bunnycdn.ru/i/cache/images/2020/03/a74e1d59b2f118aeff732cb7eb229d28.jpg",
            "type": "TV",
            "hasSub": true,
            "hasDub": false
},

### Actual behavior

Returning an error:

{
    "statusCode": 500,
    "code": "ERR_BAD_REQUEST",
    "error": "Internal Server Error",
    "message": "Request failed with status code 404"
}

### Additional context

I am using Postman to test things.

**Comment by riimuru** [comment]
Crunchyroll is dead.
