### ISSUE TITLE
FlixHq

### ISSUE THREAD

**Issue by rjcc88** [consumet/api.consumet.org#417]
### Describe the bug

not working

### Steps to reproduce

when searching access denied

### Expected behavior

..

### Actual behavior

...

**Comment by humamchoudhary** [comment]
same issue. any fixes?

**Comment by SlideMovies** [comment]
Try self-hosting it

**Comment by riimuru** [comment]
Flixhq route has been blocked due to heavy load. You need to [self-host](https://github.com/consumet/api.consumet.org#installation) for it to work.
