### ISSUE TITLE
Fmovies not working

### ISSUE THREAD

**Issue by pitsi** [consumet/api.consumet.org#428]
### Describe the bug

As mentioned in the title, the fmovies provider does not work, neither at your instance, nor at the one I host locally

### Steps to reproduce

Use the api's function to search something through fmovies. Using your instance that returns a 403 error
```
$ curl https://api.consumet.org/movies/fmovies/deadpool
{"statusCode":500,"error":"Internal Server Error","message":"Request failed with status code 403"
```
Using my instance, hosted locally
```
# curl -s http://localhost:3000/movies/fmovies/deadpool
{"statusCode":500,"error":"Internal Server Error","message":"connect ECONNREFUSED ::1:80"}

# curl -s http://localhost:3000/movies/fmovies/deadpool
{"statusCode":500,"error":"Internal Server Error","message":"connect EAFNOSUPPORT ::1:80 - Local (undefined:undefined)"}
```
The top error is with ip6 disabled (kernel parameter ipv6.disable=1), the bottom one is with ipv6 enabled.

### Expected behavior

I don't know how the results from fmovies actually look like, but I assume they should look like the ones from flixhq
```
# curl -s http://localhost:3000/movies/flixhq/deadpool
{"currentPage":1,"hasNextPage":false,"results":[{"id":"movie/watch-deadpool-19694","title":"Deadpool","url":"https://flixhq.to/movie/watch-deadpool-19694","image":"https://img.flixhq.to/xxrz/250x400/379/17/5c/175c58ef507c3b92a77825d04569a3ed/175c58ef507c3b92a77825d04569a3ed.jpg","releaseDate":"2016","type":"Movie"},{"id":"movie/watch-deadpool-2-19799","title":"Deadpool 2","url":"https://flixhq.to/movie/watch-deadpool-2-19799","image":"https://img.flixhq.to/xxrz/250x400/379/e5/6f/e56fac68a871cf787db740d4d3072603/e56fac68a871cf787db740d4d3072603.jpg","releaseDate":"2018","type":"Movie"},{"id":"movie/watch-once-upon-a-deadpool-19800","title":"Once Upon a Deadpool","url":"https://flixhq.to/movie/watch-once-upon-a-deadpool-19800","image":"https://img.flixhq.to/xxrz/250x400/379/5b/92/5b924878c80e51ff2db738eb2d55e691/5b924878c80e51ff2db738eb2d55e691.jpg","releaseDate":"2018","type":"Movie"}]}
```

### Actual behavior

See above. The reason I tried with ipv6 support disabled is explained below.

### Additional context

Flixhq returns this error and fails with anything when ipv6 is enabled. That is why I tried both providers with it being disabled. 
```
# curl -s http://localhost:3000/movies/flixhq/deadpool
{"statusCode":500,"error":"Internal Server Error","message":"connect EHOSTUNREACH (ipv6 address removed)"}
```

**Comment by pitsi** [comment]
Semi-offtopic. Because arch is on npm 8.x, I also gave alpine a try that is on npm 9.x. Both fmovies and flixhq fail with ipv6 enabled. Fmovies shows the same as above, while flixhq shows this timeout error
```
# curl -s http://localhost:3000/movies/flixhq/deadpool
{"statusCode":500,"error":"Internal Server Error","message":"Socket connection timeout"}
```

**Comment by pitsi** [comment]
Was fmovies fixed or changed since then? I just noticed that there were new commits in the repo after ~2 months of silence, so I gave it a try and it now returns this error about a maximum number of retries. It also take like 30+ seconds to reply.
```
$ curl -s https://api.consumet.org/movies/fmovies/deadpool
{"statusCode":500,"error":"Internal Server Error","message":"Reached the max retries per request limit (which is 20). Refer to \"maxRetriesPerRequest\" option for details."}
```
Sadly, I no longer have the local instance so as to test, I deleted it in late June.

**Comment by forsyth47** [comment]
Here is the self-hosted url, if you guys wanna try something https://conmet.vercel.app

I have encountered similar issue with flixhq endpoint, and I opened a issue at consumet.ts repo, since the REST API is just a wrapper for it. [issue](https://github.com/consumet/consumet.ts/issues/372)

**Comment by pitsi** [comment]
Thank you for letting me try your instance. However, it returns the same error as the one I describe at the start
```
$ curl -s https://conmet.vercel.app/movies/fmovies/deadpool
{"statusCode":500,"error":"Internal Server Error","message":"connect EAFNOSUPPORT ::1:80 - Local (undefined:undefined)"}
```
If I am doing something wrong, please tell me.

**Comment by pitsi** [comment]
Something was fixed with the last commit, the one from 2 days ago, and the api now returns something more meaningful.
```
$ curl https://api.consumet.org/movies/fmovies/deadpool
{"currentPage":1,"hasNextPage":false,"results":[]}
```
Let's hope it will really return results one day :)

**Comment by pitsi** [comment]
And today's commit increased the response time from ~30 seconds to 1+ minute! The fastest I have seen is ~25 seconds and the slowest is this ~1.5 minute delay!
```
$ curl -s -w %{time_total} https://api.consumet.org/movies/fmovies/deadpool
{"currentPage":1,"hasNextPage":false,"results":[]}
86.906209
```

**Comment by pitsi** [comment]
New week, new error :p
```
$ curl https://api.consumet.org/movies/fmovies/deadpool
{"statusCode":500,"error":"Internal Server Error","message":"write EPROTO C087EAD08C7F0000:error:0A000438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1586:SSL alert number 80\n"
```
On top of that, tmdb is now broken as well, with a 401 error for search and info 
```
$ curl https://api.consumet.org/meta/tmdb/deadpool
{"statusCode":500,"error":"Internal Server Error","message":"Request failed with status code 401"}
$ curl https://api.consumet.org/meta/tmdb/info/293660?type=movie
{"statusCode":500,"error":"Internal Server Error","message":"Request failed with status code 401"}
```

**Comment by pitsi** [comment]
And the watch function for tmdb is now broken too :(
```
$ curl https://api.consumet.org/meta/tmdb/watch/19694?id=movie/watch-deadpool-19694
{"message":{}
```

**Comment by pitsi** [comment]
@forsyth47 
Sorry for the 4-month late question. Do you still update your self-hosted instance?
I still can not host my own, so I can not check if anything has changed after all those commits, but fmovies still gives the same error as before at your instance.

**Comment by pitsi** [comment]
Today, 1 year after opening the issue, I had the chance of making a new vm to test if anything has changed. And sadly nothing has changed, fmovies remains broken, and it even has the same errors like last year :(

Libgen is also broken.

**Comment by pitsi** [comment]
With fmovies dead and buried for almost a month now, there is no reason to keep this open. After all, it never worked.
