### ISSUE TITLE
Unable to get anime streaming link in gogoanime and anilist

### ISSUE THREAD

**Issue by ShivaBhattacharjee** [consumet/api.consumet.org#436]
### Describe the bug

when i send a get request in /anime/gogoanime/watch/spy-x-oshi-no-ko-episode-1 its not returning the streaming link

### Steps to reproduce

Send a get request in /anime/gogoanime/watch/spy-x-oshi-no-ko-episode-1 or /meta/anilist/watch/spy-x-oshi-no-ko-episode-1

it wont return any response

### Expected behavior

{
  "headers": {
      "Referer": "string",
      "watchsb": "string", // or null, since only provided with server being equal to "streamsb".
      "User-Agent": "string" // or null
  },
  "sources": [
      {
      "url": "string",
      "quality": "string",
      "isM3U8": true
      }
  ]
}

### Actual behavior

{"message":{}}

**Comment by Dovakiin0** [comment]
Server is down

**Comment by ShivaBhattacharjee** [comment]
i have self hosted the api is gogoanime do
wn?

**Comment by gaminglnk** [comment]
Yes I've also self hosted the API.
I think the GogoAnime domain used to fetch episode is not working.

**Comment by saurabhgangule** [comment]
Guys, got any solution?

**Comment by ShivaBhattacharjee** [comment]
> Guys, got any solution?

I think we need to switch to zoro for the time being lets see if that works

**Comment by ShivaBhattacharjee** [comment]
> How are you guys, still streaming content in your websites, when the api is down, sorry i am not experinced in web development

you can self host the api 

here my repo https://github.com/ShivaBhattacharjee/AnimeTrix
fixed streaming using amvstram

**Comment by JayadityaGit** [comment]
After seeing your project I got motivation to create my project , here is the problem, I recently learned MERN stack from udemy
and found this api, what I did was , I was fetching data using the server and sending it to the frontend and I am using mongodb to store users for auth and thier favorites, I was using zoro one till yesterday and it was working but today it stopped working suddenly... should I make my project open source, so u can give me some guidance bro? I asked Chatgpt about self hosting but my I can only see stars in my head , can you  share some resource to learn self hosting. 

Thx for your inspiration bro,
started following you on github recently

**Comment by ShivaBhattacharjee** [comment]
You can add ?provider=zoro in the url of detail page and get the data using zoro streaming api in streame page

**Comment by gaminglnk** [comment]
> > Yeah, check out https://kimitsu-beta.vercel.app/ I just changed the method of scraping to Zoro and it works so smooth.
> 
> How did you convert AniList id to Zoro id? Did you just make a search with it from the anime name?

To get Zoro or Gogo ID for a particular anime through Anilist Id, we use a mapping service like MALSync (one which is used by Consumet)

This matches many aspects of an anime with ones which are available on Zoro or Gogo and gives a match if found.

Consumet API already does this, just try requesting and on route `/meta/anilist/episodes/{your_anime_id}?provider=zoro` and it will list all available episodes.

**Comment by JayadityaGit** [comment]
Yeah I got it !, I will defnitely make it open source when i implement the basic features for a anime streaming website, glad I found some people who resonate with me , now having my 2nd year sem exams , too busy for now, but yeah thanks for your generous guidance man. I feel so stupid not even looking at the doc of the repo haha.

**Comment by ShivaBhattacharjee** [comment]
> Yeah I got it !, I will defnitely make it open source when i implement the basic features for a anime streaming website, glad I found some people who resonate with me , now having my 2nd year sem exams , too busy for now, but yeah thanks for your generous guidance man. I feel so stupid not even looking at the doc of the repo haha. Maybe we could Network , grow and share together ...

Sure we can network heres a link to my portfolio

https://immashiva.vercel.app/

**Comment by riimuru** [comment]
The issue has been fixed. Sorry for the inconvenience.
