### ISSUE TITLE
gogoanime /watch host error 

### ISSUE THREAD

**Issue by SocialDropout** [consumet/api.consumet.org#456]
### Describe the bug

Gogoanime's stream links endpoint (/watch) gives bad gateway error.

### Steps to reproduce

Try to get stream links for any ep in gogoanime.

Example:
``https://api.consumet.org/anime/gogoanime/watch/isekai-de-cheat-skill-wo-te-ni-shita-ore-wa-genjitsu-sekai-wo-mo-musou-suru-level-up-wa-jinsei-wo-kaeta-episode-10``

### Expected behavior

Should respond with available stream links or a message in json format.

### Actual behavior

Gives bad gateway host error instead.

**Comment by riimuru** [comment]
@SocialDropout it works fine now.
