### ISSUE TITLE
Image Proxy 400 error

### ISSUE THREAD

**Issue by Yash1907** [consumet/api.consumet.org#465]
### Describe the bug

https://api.consumet.org/utils/image-proxy?url=image_url&referer=image_referer_url doesn't work.

### Steps to reproduce

1.  `await fetch("https://api.consumet.org/utils/image-proxy?url=https://zjcdn.mangahere.org/store/manga/32140/074.0/compressed/lspy_x_family_074_001.jpg, {
    "headers": {"Referer":"http://www.mangahere.cc/manga/spy_x_family/c074/1.html"}`

### Expected behavior

200 ok

### Actual behavior

400 error

### Additional context

I tried ` await fetch("https://api.consumet.org/utils/image-proxy?url=https://zjcdn.mangahere.org/store/manga/32140/074.0/compressed/lspy_x_family_074_001.jpg&headers=http://www.mangahere.cc/manga/spy_x_family/c074/1.html", {
    "headers": {"Referer":"http://www.mangahere.cc/manga/spy_x_family/c074/1.html"}`
which gives me a 500 any help is appreciated its probably some dumb mistake.

**Comment by riimuru** [comment]
@Yash1907 Use it like this
```
https://api.consumet.org/utils/image-proxy?url=https://zjcdn.mangahere.org/store/manga/32140/074.0/compressed/lspy_x_family_074_001.jpg&headers={"referer": "http://www.mangahere.cc/manga/spy_x_family/c074/1.html"}
```
