### ISSUE TITLE
Zoro anime info route not working

### ISSUE THREAD

**Issue by ghoshRitesh12** [consumet/api.consumet.org#468]
### Describe the bug

The anime info route of zoro provider is not working. Its always giving 404 status code with an empty object having an empty message property.

### Steps to reproduce

1. Go to [this zoro anime info provider route](https://api.consumet.org/anime/zoro/info?id=steinsgate-3)
1. You will get a `{ "message": { } }` as response & the status code is `404`

### Expected behavior

Should show info about the anime that is being seached for if it exists.
For eg. I searched for Steins Gate, so it should information about Steins Gate. Information like its Studio, Genres, etc.

### Actual behavior

Should show info about the anime that is being seached for if it exists.
For eg. I searched for Steins Gate, so it should information about Steins Gate. Information like its Studio, Genres, etc.

**Comment by Naiml007** [comment]
zoro .to shutdown there domain now it's called aniwatch

**Comment by riimuru** [comment]
The issue have been fixed.
