### ISSUE TITLE
Invalid id from gogoanime Get Recent Episodes

### ISSUE THREAD

**Issue by detecto452** [consumet/api.consumet.org#473]
### Describe the bug

There are cases where the id from recent episodes and the real anime id don't match.

### Steps to reproduce

Episode JSON data from https://api.consumet.org/anime/gogoanime/recent-episodes?page=4
(Page numbers may change over time.)

...
{
"id":"jujutsu-kaisen-2nd-season",
"episodeId":"jujutsu-kaisen-2nd-season-episode-3",
"episodeNumber":3,
"title":"Jujutsu Kaisen 2nd Season",
"image":"https://gogocdn.net/cover/jujutsu-kaisen-tv-2nd-season-1688154932.png",
"url":"https://gogoanimehd.to/jujutsu-kaisen-2nd-season-episode-3"
}
...

### Expected behavior

If my understanding is correct, the gogoanime id for 'Jujutsu Kaisen 2nd Season' is 'jujutsu-kaisen-2nd-season' from the above data.

So the url to get its anime info should be this.

https://api.consumet.org/anime/gogoanime/info/jujutsu-kaisen-2nd-season

### Actual behavior

https://api.consumet.org/anime/gogoanime/info/jujutsu-kaisen-2nd-season

{"message":{}}

### Additional context

The correct id is 'jujutsu-kaisen-tv-2nd-season'. 

https://api.consumet.org/anime/gogoanime/info/jujutsu-kaisen-tv-2nd-season

{"id":"jujutsu-kaisen-tv-2nd-season","title":"Jujutsu Kaisen 2nd Season","url":"/category/jujutsu-kaisen-tv-2nd-season","genres":["Action","Fantasy","School","Shounen"],"totalEpisodes":3,"image":"https://gogocdn.net/cover/jujutsu-kaisen-tv-2nd-season-1688154932.png","releaseDate":"2023","description":"Second season of Jujutsu Kaisen.","subOrDub":"sub","type":"SUMMER 2023 ANIME","status":"Ongoing","otherName":"呪術廻戦 2 / 咒術迴戰第二季 / 咒術迴戰 2 / 주술회전 2기 / Sorcery Fight / JJK / Jujutsu Kaisen (TV) 2nd Season / มหาเวทย์ผนึกมาร ซีซั่น 2","episodes":[{"id":"jujutsu-kaisen-2nd-season-episode-1","number":1,"url":"https://gogoanimehd.to//jujutsu-kaisen-2nd-season-episode-1"},{"id":"jujutsu-kaisen-2nd-season-episode-2","number":2,"url":"https://gogoanimehd.to//jujutsu-kaisen-2nd-season-episode-2"},{"id":"jujutsu-kaisen-2nd-season-episode-3","number":3,"url":"https://gogoanimehd.to//jujutsu-kaisen-2nd-season-episode-3"}]}

jujutsu-kaisen-2nd-season
jujutsu-kaisen-tv-2nd-season

Unlike the id from recent episodes data, the correct id contains '-tv-' in the slug.
Is this also considered as a bug?

**Comment by riimuru** [comment]
https://github.com/consumet/api.consumet.org/issues/525#issuecomment-1813345359
> This is honestly a gogoanime issue, as you can't always get the accurate anime from the recent page. You could make an exception case for this kind of issue when looping through the recent list, like 
> ```
> if anime.id == "16bit-sensation-another-layer": 
>    anime.id = 16bit-sensation
> ```
> This is a rare case so its fine if you hard-code these cases.
