### ISSUE TITLE
Something went wrong. Please try again later.

### ISSUE THREAD

**Issue by Proff-Roman** [consumet/api.consumet.org#477]
### Describe the bug

It gives an error "Something went wrong. Please try again later.", any idea how to fix it?

### Steps to reproduce

**Request:** http://127.0.0.1:3000/movies/flixhq/watch?episodeId=7230&mediaId=movie/watch-project-xtraction-7230

### Expected behavior

{
    "headers": {
        "Referer": "string"
    },
    "sources": [
        {
        "url": "string",
        "quality": "string",
        "isM3U8": true
        }
    ],
    "subtitles": [
        {
        "url": "string",
        "lang": "string"
        }
    ]
}

### Actual behavior

{"message":"Something went wrong. Please try again later."}

### Additional context

??

**Comment by riimuru** [comment]
use this (I just tested it and it works!)

/movies/flixhq/watch?episodeId=7230&mediaId=movie/watch-project-xtraction-7230&server=vidcloud
make sure you have the "server" parameter at the end!
