### ISSUE TITLE
Reached the max retries per request limit (which is 20). Refer to "maxRetriesPerRequest" option for details.

### ISSUE THREAD

**Issue by sonicjhon1** [consumet/api.consumet.org#479]
### Describe the bug

Simply fetching "https://api.consumet.org/meta/anilist/info/21" returns ```{"message":"Reached the max retries per request limit (which is 20). Refer to \"maxRetriesPerRequest\" option for details."}```

### Steps to reproduce

1. Fetch https://api.consumet.org/meta/anilist/info/21
2. `{"message":"Reached the max retries per request limit (which is 20). Refer to \"maxRetriesPerRequest\" option for details."}`

### Expected behavior

Based on https://docs.consumet.org/rest-api/Meta/anilist-anime/get-anime-info#request-samples, it should return what's shown on https://docs.consumet.org/rest-api/Meta/anilist-anime/get-anime-info#response-schema.

### Actual behavior

After waiting for a while, the API returns `{"message":"Reached the max retries per request limit (which is 20). Refer to \"maxRetriesPerRequest\" option for details."}`

**Comment by riimuru** [comment]
@sonicjhon1 The API has been getting DDOS'd for many months now, which is why there's many issues on the public api. I suggest [self-hosting](https://github.com/consumet/api.consumet.org#installation) the API. Or using [consumet.ts](https://github.com/consumet/consumet.ts) library.
