### ISSUE TITLE
Anilist /info and search endpoints not working

### ISSUE THREAD

**Issue by Anuragkumarsah** [consumet/api.consumet.org#485]
### Describe the bug

Anilist giving 408 status code "Request Timeout" for info, search and streaming episode link endpoints

### Steps to reproduce

Request: https://api.consumet.org/meta/anilist/watch/21355
Or
Request: https://api.consumet.org/meta/anilist/info/21355
Or
Request: https://api.consumet.org/meta/anilist/ReZero

### Expected behavior

{
"currentPage": 1,
"results": [
    {
      "id": "string",
      "title": "string",
      "image": "string",
      "type": "string",
      "rating": "number",
      "releaseDate": "string"
    }
  ]
}

### Actual behavior

{
  "message": "Something went wrong. Contact developer for help."
}

Or sometimes

408 Request Timeout Response

{
  "error": "Request Timeout",
  "message": "Client Timeout",
  "statusCode": 408
}

**Comment by bharathmsd7** [comment]
Facing same issue.

**Comment by riimuru** [comment]
@Anuragkumarsah Thank you for reporting the issue! the API is working fine now. But if you encounter any similar issues in the future, please try [self-hosting](https://github.com/consumet/api.consumet.org#installation) the API.
