### ISSUE TITLE
FlixHQ

### ISSUE THREAD

**Issue by Cimasearch** [consumet/api.consumet.org#521]
Everything is working fine but when grabbing the links getting error {"message":"Something went wrong. Please try again later."}

movies/flixhq/watch?episodeId=98446&mediaId=movie/watch-oppenheimer-98446

**Comment by ramonporterusa** [comment]
I think an error is happening for this: https://github.com/consumet/consumet.ts/blob/master/src/extractors/vidcloud.ts  On this file, there is this link: https://github.com/enimax-anime/key/blob/e4/key.txt and https://raw.githubusercontent.com/enimax-anime/key/e4/key.txt, and it shows a 404: Not Found  or removed; that is why streaming m3u8 link are not able to be extracted.

**Comment by riimuru** [comment]
@Cimasearch use this (I just tested it and it works!)
```
/movies/flixhq/watch?episodeId=98446&mediaId=movie/watch-oppenheimer-98446&server=vidcloud
``` 
make sure you have the "server" parameter at the end!
