### ISSUE TITLE
16bit-sensation-another-layer anime ID is wrong in recent-episodes endpoint , Please deploy a fix ASAP

### ISSUE THREAD

**Issue by Abhinavkuamr** [consumet/api.consumet.org#525]
### Describe the bug

Anime's ID is wrong in recent-episode endpoint 

### Steps to reproduce

1. Goto this endpoint https://api.consumet.org/anime/gogoanime/recent-episodes
2. check the ID is given 16bit-sensation-another-layer

But when u search for info for that anime with this https://api.consumet.org/anime/gogoanime/info/16bit-sensation-another-layer
it gives {} , empty object
because the Correct id is this 
https://api.consumet.org/anime/gogoanime/info/16bit-sensation

### Expected behavior

Set the ID to 16bit-sensation

in /recent-episodes endpoint

### Actual behavior

Its showing ID as this "16bit-sensation-another-layer" 

in /recent-episodes endpoint

**Comment by riimuru** [comment]
@Abhinavkuamr This is honestly a gogoanime issue, as you can't always get the accurate anime from the recent page. You could make an exception case for this kind of issue when looping through the recent list, like 
```
if anime.id == "16bit-sensation-another-layer": 
   anime.id = 16bit-sensation
```
This is a rare case so its fine if you hard-code these cases.

**Comment by riimuru** [comment]
https://github.com/consumet/api.consumet.org/issues/473
