### ISSUE TITLE
Zoro 404 Error while fetching episode links

### ISSUE THREAD

**Issue by Dextron04** [consumet/api.consumet.org#526]
### Describe the bug

While working with the streaming links the links give an error and the link that the provided in the schema is different from the one that we have to use.

### Steps to reproduce

In the Zoro's  Streaming Links section the router schema is this: `https://api.consumet.org/anime/zoro/watch/{episodeId}?server={serverName}
`
The url used in the example is: `https://api.consumet.org/anime/zoro/watch?episodeId=spy-x-family-17977$episode$89506$both&server=vidcloud`

Mentioned in: [https://docs.consumet.org/rest-api/Anime/zoro/get-anime-episode-streaming-links](url)

### Expected behavior

`{
  "headers": {
      "Referer": "string",
      "watchsb": "string", // or null, since only provided with server being equal to "streamsb".
      "User-Agent": "string" // or null
  },
  "sources": [
      {
      "url": "string",
      "quality": "string",
      "isM3U8": true
      }
  ]
}
`

### Actual behavior

`{
  "message": {
    "message": "Request failed with status code 404",
    "name": "AxiosError",
    "config": {
      "transitional": {
        "silentJSONParsing": true,
        "forcedJSONParsing": true,
        "clarifyTimeoutError": false
      },
      "transformRequest": [null],
      "transformResponse": [null],
      "timeout": 0,
      "xsrfCookieName": "XSRF-TOKEN",
      "xsrfHeaderName": "X-XSRF-TOKEN",
      "maxContentLength": -1,
      "maxBodyLength": -1,
      "env": {},
      "headers": {
        "Accept": "application/json, text/plain, */*",
        "User-Agent": "axios/0.27.2"
      },
      "method": "get",
      "url": "https://github.com/enimax-anime/key/blob/e6/key.txt"
    },
    "code": "ERR_BAD_REQUEST",
    "status": 404
  }
}
`

### Additional context

I have tried to manipulate the url multiple times but it just doesn't work either it gives me an empty message object or it gives me the 404 error.

**Comment by FlawLessx** [comment]
the author removed repository https://github.com/enimax-anime/key/blob/e6/key.txt, currently no one provide rapidvideo key

**Comment by riimuru** [comment]
@Dextron04 @FlawLessx  I just tested the api locally, and everything seems to work fine. Make sure to update the dependencies to stay up to date with the consumet.ts code.
```js
yarn upgrade //or npm update
```

**Comment by FlawLessx** [comment]
@riimuru try open this https://api.consumet.org/anime/zoro/watch?episodeId=spy-x-family-17977$episode$89506$both&server=vidcloud

**Comment by riimuru** [comment]
@FlawLessx The API is [not updated](https://github.com/consumet/api.consumet.org/issues/486) that's why it's not working there, but if you self-host or try it locally it will work!

**Comment by Dextron04** [comment]
@riimuru Thank You for the response!. I just had one question how do I access the api (Not locally) so that I can use it in production as I'm building a full fledged application. How do I get the 5 hour access that you talk about in this discussion. ([https://github.com/consumet/api.consumet.org/issues/486](https://github.com/consumet/api.consumet.org/issues/486))

**Comment by riimuru** [comment]
@Dextron04 Since you want to use it for production, please self-host it using one of the following services here: https://github.com/consumet/api.consumet.org#vercel they're free!

**Comment by Dextron04** [comment]
@riimuru Okay Got it!! Thanks for the help
