### ISSUE TITLE
Gogoanime has change Domain to anitaku.to

### ISSUE THREAD

**Issue by Brent001** [consumet/api.consumet.org#534]
### Describe the bug

The gogoanimehd.io is not working 

### Steps to reproduce

the provider change domain

### Expected behavior

it should the anime to show

### Actual behavior

but the episode don't load because the provider domain has change

### Additional context

also the 9anime domain has change to 9anime.id to aniwave.to

**Comment by babsonnexus** [comment]
Concur, the API is returning an incorrect URL:

![image](https://github.com/consumet/api.consumet.org/assets/24477898/29ec39d4-ac53-4b1b-8d16-2af447b5c63c)

You can see it here:

![image](https://github.com/consumet/api.consumet.org/assets/24477898/b2d0e204-2202-4aec-ba00-bbea2ceb9e72)

Changing the line to this seems to fix all the issues:

![image](https://github.com/consumet/api.consumet.org/assets/24477898/70942923-f8b9-4a43-abbf-9a5b01aa55f3)

**Comment by riimuru** [comment]
@babsonnexus @Brent001 This issue has been fixed, Sorry for the wait. if you're using the docker image maker sure to pull a new fresh install. And if you're using the source code directly make sure to upgrade the packages.
