### ISSUE TITLE
gogoanime indeed changed it's ip but real gogoanime link is :https://gogoanime3.net

### ISSUE THREAD

**Issue by animegers** [consumet/api.consumet.org#539]
### Describe the bug

anime is not loading or appearing 

### Steps to reproduce

1. recently added anime not appearing
2. anime category not working
3. recently sub/dub anime also not working.

### Expected behavior

till gogoanime changed it's ip it was working fine as expected.

### Actual behavior

due to ip change it's struggling to find anime there's a lot of errors....i saw someone said they changed it to anitaku.to but their real domain was gogoanime.tv and now when you search it it redirects to https://gogoanime3.net/ so if mods are working on it work with this url to extract information....

**Comment by riimuru** [comment]
@animegers Thank you for your report! The issue has been fixed 👍
