### ISSUE TITLE
meta/anilist endpoint not working

### ISSUE THREAD

**Issue by Noname968** [consumet/api.consumet.org#549]
### Describe the bug

The endpoint does not fetch data for anime. For some anime it fetches episodes and for some anime it gives an error.

### Steps to reproduce

https://consumet-anime-api.vercel.app/meta/anilist/info/21

### Expected behavior

Should fetch data

### Actual behavior

{
  "message": "Cannot read properties of null (reading 'length')"
}

**Comment by Jordi-Jaspers** [comment]
This should be solved in the latest version. If running a docker image. remove the cache and rebuild after pulling the latest.
