### ISSUE TITLE
movies/flixhq/watch endpoint not working

### ISSUE THREAD

**Issue by VISHWAJ33T** [consumet/api.consumet.org#554]
### Describe the bug

This endpoint is not fetching episode streaming links

### Steps to reproduce

https://conmet.vercel.app/movies/flixhq/watch?episodeId=10766&mediaId=tv/watch-rick-and-morty-39480

### Expected behavior

This should fetch data

### Actual behavior

{"message":"Something went wrong. Please try again later."}

**Comment by ClayArsenio26** [comment]
I have tested on vps, I think they are limited. In some days its work well and after 3 days any issue with msg: {"message":"Something went wrong. Please try again later."}

**Comment by snoofox** [comment]
so what can we do about it? like it's the only good provider for movies, we need an good replacement or fix this one somehow.

**Comment by emmagrove** [comment]
Same problem here. I think the api is just broken and it's been this way for a few months now. I've seen a couples website that's using the same api and somehow still able to fetch data but I couldn't figure out how they doing it. braflix.app is one them.

**Comment by RajatavaMahajan** [comment]
if you somehow change the targetted url it will work

**Comment by ClayArsenio26** [comment]
> if you somehow change the targetted url it will work

what is target url ? give me example?

**Comment by Sisableng** [comment]
> if you somehow change the targetted url it will work

do you mean the api endpoint?

**Comment by ClayArsenio26** [comment]
> if you somehow change the targetted url it will work

yess the api end point, I have facing a problem in my application from pull with docker request, can't work anytime it appear msg 

{
  "message": "Something went wrong. Please try again later."
}

please fix this I saw at last day till now, before last day is work well. please sir fix this @snoofox snoofox

**Comment by ClayArsenio26** [comment]
please fix the movies and tv shows flixhq any error

**Comment by BeamlakAschalew** [comment]
> please fix the movies and tv shows flixhq any issue on access source video, in parameter watch?episodeId=166&mediaId=movie/watch-endgame-166&server=upcloud or vidcloud, only it all work well to access info detail searching query. I have tested on node and docker all of these request on video source don't work with msg "{"message": "Something went wrong. Please try again later."}

Redelopy your api instance, the consumet.ts library is updated so it'll work if you re-install the consumet.ts package

**Comment by VISHWAJ33T** [comment]
@BeamlakAschalew yes it is working fine now
