### ISSUE TITLE
FlixHQ Episode Streaming Links not working

### ISSUE THREAD

**Issue by fsmdeveloper** [consumet/api.consumet.org#569]
### Describe the bug

FlixHQ Episode Streaming Links not working

### Steps to reproduce

`{{BASE_URL}}/movies/flixhq/watch?episodeId=10766&mediaId=tv/watch-rick-and-morty-39480&server=upcloud`

**response : {
    "message": "Something went wrong. Please try again later."
}**

### Expected behavior

it was working before, but now it's not working, I have also tried consumet.ts package, but It's also not working, what is the problem?? any other alternative options?

### Actual behavior

response : {
    "message": "Something went wrong. Please try again later."
}

**Comment by Shafiq-GH** [comment]
i assume its due to the keys because https://keys4.fun/ is currently down. Wait for update i guess

**Comment by fsmdeveloper** [comment]
Thank you for your valuable info

**Comment by steveyout** [comment]
Getting the same issue here

**Comment by fsmdeveloper** [comment]
https://keys4.fun/ is up and running, but it still has the same issue, please someone fix the issue

**Comment by ClayArsenio26** [comment]
> Although https://keys4.fun/ is up and running, it still has the same issue. Could someone please fix it?

have you try some other provider movies & tv shows that is goku in consumet.ts ?? its working or not buddy ??

**Comment by ClayArsenio26** [comment]
@riimuru hello sir please add provider goku.sx in api.consumet.org, so I will use goku provider to handdle provide movies  tv shows cause we have waited from client for somedays there is no fix it please !

**Comment by dhelbegor** [comment]
I just created a PR to solve the problem.
https://github.com/consumet/consumet.ts/pull/478

Hope that this can solve it.

**Comment by fsmdeveloper** [comment]
> > Although https://keys4.fun/ is up and running, it still has the same issue. Could someone please fix it?
> 
> have you try some other provider movies & tv shows that is goku in consumet.ts ?? its working or not buddy ??

no! not working. same error from goku and other providers

**Comment by ClayArsenio26** [comment]
> > > Although https://keys4.fun/ is up and running, it still has the same issue. Could someone please fix it?
> > 
> > 
> > have you try some other provider movies & tv shows that is goku in consumet.ts ?? its working or not buddy ??
> 
> no! not working. same error from goku and other providers

bro share ur telegram user name, I will sharring with u

**Comment by fsmdeveloper** [comment]
> > > > Although https://keys4.fun/ is up and running, it still has the same issue. Could someone please fix it?
> > > 
> > > 
> > > have you try some other provider movies & tv shows that is goku in consumet.ts ?? its working or not buddy ??
> > 
> > 
> > no! not working. same error from goku and other providers
> 
> bro share ur telegram user name, I will sharring with u

what will you share?

**Comment by VISHWAJ33T** [comment]
it is still not working

**Comment by fsmdeveloper** [comment]
yes! it's not working!!
