### ISSUE TITLE
Deployment on vercel not working

### ISSUE THREAD

**Issue by streamamos** [consumet/api.consumet.org#570]
### Describe the bug

Deploying the api on vercel it crashes vercel

### Steps to reproduce

1. Deploy api.consumet.org to Vercel
2. Get error

### Expected behavior

The api should appear saying "Welcome to the api"

### Actual behavior

When accessing the api it gives this:

This Serverless Function has crashed.
Your connection is working correctly.
Vercel is working correctly.
500: INTERNAL_SERVER_ERROR
Code: FUNCTION_INVOCATION_FAILED

### Additional context

This is the logs from vercel:

Invalid export found in module "/var/task/src/main.js".
The default export must be a function or server.
INIT_REPORT Init Duration: 868.45 ms    Phase: init    Status: error    Error Type: Runtime.ExitError
Invalid export found in module "/var/task/src/main.js".
The default export must be a function or server.
INIT_REPORT Init Duration: 1501.21 ms    Phase: invoke    Status: error    Error Type: Runtime.ExitError
Error: Runtime exited with error: exit status 1
Runtime.ExitError

**Comment by d3vAdrian** [comment]
same error but running locally

**Comment by Amritanshu312** [comment]
same here The Error is
 "Invalid export found in module "/var/task/src/main.js".
The default export must be a function or server.
INIT_REPORT Init Duration: 1530.42 ms	Phase: invoke	Status: error	Error Type: Runtime.ExitError
Error: Runtime exited with error: exit status 1
Runtime.ExitError
"
![Screenshot 2024-02-25 130133](https://github.com/consumet/api.consumet.org/assets/96000113/3514a4e1-f2f0-4786-8d71-9785e9356d39)
