### ISSUE TITLE
gogoanime info api not working

### ISSUE THREAD

**Issue by ks3rr** [consumet/api.consumet.org#574]
### Describe the bug

gogoanime info api not working

### Steps to reproduce

calling info api of gogoanime returns empty 

### Expected behavior

should return info of anime

### Actual behavior

returning empty

**Comment by kurays015** [comment]
How about the episodes being empty? is it provider's problem?

**Comment by riimuru** [comment]
This should be solved in the latest version. If running a docker image. remove the cache and rebuild after pulling the latest. otherwise run `yarn upgrade` or `npm update`
