### ISSUE TITLE
The episodes array suddenly became empty. (Meta and Gogoanime)

### ISSUE THREAD

**Issue by kurays015** [consumet/api.consumet.org#576]
### Describe the bug

Episodes array is suddenly empty.

### Steps to reproduce

empty episodes array

### Expected behavior

Has episodes

### Actual behavior

Empty episodes

### Additional context

Also when when fetching /watch/anime-episode endpoint, it's status 200.

**Comment by Babyyoda777** [comment]
Seeing same issue, retrieving info on anime using GogoAnime just gives empty message:

**Comment by devpapi0891** [comment]
Same here. Just now.

**Comment by kurays015** [comment]
I host an instance of Consumet API again in onrender and it's now working.

**Comment by Babyyoda777** [comment]
Would you be able to share the link briefly? @kurays015

**Comment by kurays015** [comment]
@Babyyoda777 go here https://github.com/consumet/api.consumet.org and click deploy to render button at the bottom or other platform.

**Comment by protwan** [comment]
I had the same problem. I forgot to run `npm update` after `git pull`
