### ISSUE TITLE
No episodes and not working Gogoanime servers

### ISSUE THREAD

**Issue by Brent001** [consumet/api.consumet.org#578]
### Describe the bug

The gogoanimehd.io is not working 

### Steps to reproduce

https:/example.api.com/anime/gogoanime/top-airing

Output:
{"message":"Something went wrong. Contact developers for help."}

### Expected behavior

Show all links in top airing anime in gogoanime servers

### Actual behavior

{"message":"Something went wrong. Contact developers for help."}

**Comment by fsmdeveloper** [comment]
same issue with FlixHQ

**Comment by riimuru** [comment]
This should be solved in the latest version. If running a docker image. remove the cache and rebuild after pulling the latest. otherwise run `yarn upgrade` or `npm update`
