### ISSUE TITLE
Unable to fetch anime through anilist meta client on vercel

### ISSUE THREAD

**Issue by iamkingarthur** [consumet/api.consumet.org#591]
### Describe the bug

after hosting it on vercel when we send a get request at eg.vercel.app/meta/anilist/21 it returns  {"level":30,"time":1711650581420,"pid":8,"hostname":"169.254.41.173","reqId":"req-2","req":{"method":"GET","url":"/meta/anilist/info/101922","hostname":"api-consumet-org-sand.vercel.app","remoteAddress":"127.0.0.1","remotePort":34324},"msg":"incoming request"} {"level":30,"time":1711650581887,"pid":8,"hostname":"169.254.41.173","reqId":"req-2","res":{"statusCode":200},"responseTime":466.92872200000056,"msg":"request completed"} Response payload too large

### Steps to reproduce

send a get request at hostedapp.vercel.app/meta/anilist/info/21
the server less function crashes after inspecting server logs i see this

{"level":30,"time":1711650581420,"pid":8,"hostname":"169.254.41.173","reqId":"req-2","req":{"method":"GET","url":"/meta/anilist/info/101922","hostname":"api-consumet-org-sand.vercel.app","remoteAddress":"127.0.0.1","remotePort":34324},"msg":"incoming request"}
{"level":30,"time":1711650581887,"pid":8,"hostname":"169.254.41.173","reqId":"req-2","res":{"statusCode":200},"responseTime":466.92872200000056,"msg":"request completed"}
Response payload too large

### Expected behavior

Should return anime info

### Actual behavior

{"level":30,"time":1711650581420,"pid":8,"hostname":"169.254.41.173","reqId":"req-2","req":{"method":"GET","url":"/meta/anilist/info/101922","hostname":"api-consumet-org-sand.vercel.app","remoteAddress":"127.0.0.1","remotePort":34324},"msg":"incoming request"}
{"level":30,"time":1711650581887,"pid":8,"hostname":"169.254.41.173","reqId":"req-2","res":{"statusCode":200},"responseTime":466.92872200000056,"msg":"request completed"}
Response payload too large

**Comment by yusuftuncay** [comment]
I have the exact same, if you still want it working, you can use the endpoint ```eg.vercel.app/meta/anilist/EPISODES/21```. I don't know if this is usefull to you but it was a perfect workaround for my situation till this gets fixed. (this endpoint doesn't return info obviously)

**Comment by riimuru** [comment]
@iamkingarthur @yusuftuncay you can use /meta/anilist/data/21 for the metadata, this is not an API issue; vercel restricts large responses.

**Comment by iamkingarthur** [comment]
> @iamkingarthur @yusuftuncay you can use `/meta/anilist/episodes/21` for episodes and `/meta/anilist/data/21` for the metadata, this is not an API issue; vercel restricts large responses.

it worked fine in earlier versions
