### ISSUE TITLE
Cannot read properties of undefined (reading 'Media')

### ISSUE THREAD

**Issue by ShivaBhattacharjee** [consumet/api.consumet.org#601]
### Describe the bug

Get request at meta provider returns http://localhost:6969/meta/anilist/info/101922 returns a undefined mediia error 

### Steps to reproduce

send a get request to 
https://http:localhost:3000/meta/anilist/info/101922
it returns 
{"message":"Cannot read properties of undefined (reading 'Media')"}
instead of anime details

### Expected behavior

An array containing anime information

### Actual behavior

{"message":"Cannot read properties of undefined (reading 'Media')"}

**Comment by riimuru** [comment]
Should have been working! works on my end, make sure to stay up to date using `yarn upgrade` or `npm update`
