### ISSUE TITLE
what happened to movie-web? all repositories are gone.

### ISSUE THREAD

**Issue by fsmdeveloper** [consumet/api.consumet.org#606]
### Describe the bug

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

### Steps to reproduce

--------------------

### Expected behavior

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

### Actual behavior

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

### Additional context

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by pitsi** [comment]
I think this answers your question fully.
https://old.reddit.com/r/Piracy/comments/1cbd9g7/rip_movieweb_truly_one_of_the_goat/

Please do not spam an unrelated project again. Thank you :)

**Comment by fsmdeveloper** [comment]
Sorry, I didn't check the Reddit. btw, thanks
