### ISSUE TITLE
Episodes endpoint not working for anilist meta

### ISSUE THREAD

**Issue by DattebayoVinayak** [consumet/api.consumet.org#621]
### Describe the bug

Provider was anilist

### Steps to reproduce

1. Go to ''/meta/anilist/episodes/21'' 

### Expected behavior

To get episodes

### Actual behavior

Got
{"message":"Anime not found"}

### Additional context

Please solve this bug

**Comment by DattebayoVinayak** [comment]
Have you fixed it @riimuru

**Comment by jef-design** [comment]
@DattebayoVinayak hey did you fixed?

**Comment by TropicLegend** [comment]
I am experiencing the same issue.
