### ISSUE TITLE
"Anime not found" Message upon requesting /meta/anilist/episodes/{Any Anilist ID}?provider=gogoanime

### ISSUE THREAD

**Issue by TropicLegend** [consumet/api.consumet.org#636]
### Describe the bug

Upon requesting paths like "/meta/anilist/episodes/20?provider=gogoanime" and any similar (Every Anilist ID has the same problem) -> the message "Anime not found" is responded with instead of the actual json data

### Steps to reproduce

1) Setup consumet-api with `docker run -p 3000:3000 riimuru/consumet-api`
2) Request e.g. `http://0.0.0.0:3000/meta/anilist/episodes/20?provider=gogoanime&dub=false`
3) Get error `{"message":"Anime not found"}` instead of actual response.

It does not matter whether one accesses &dub=false or &dub=true in this case.

### Expected behavior

I expect to get the json data for the gogoanime episodes.

### Actual behavior

I get the error `{"message":"Anime not found"}`.

**Comment by TropicLegend** [comment]
An important detail is that this route has worked just a few days (like a week) ago.
It has stopped working suddenly and seemingly without reason.

**Comment by yusuftuncay** [comment]
Same issue

**Comment by lqs-1** [comment]
Same issue

**Comment by ProudlyTM** [comment]
The issue seems to be back.
